spring:
  datasource:
    url: jdbc:mysql://acg6138.czyfxvmdjeap.ap-northeast-2.rds.amazonaws.com:3306/jocoding?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: acg6138
    password: wjddn6138
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto : update
      default_batch_fetch_size: 100
    properties:
      hibernate:
        format_sql: true
cloud:
  aws:
    credentials:
      accessKey: AKIAZ2TLOPBR6WNJBQXJ
      secretKey: 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
    s3:
      bucket: celebrem
    region:
      static: ap-northeast-2
    stack:
      auto: false
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secret: dcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcoding

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 20MB
