spring:
  datasource:
    url: jdbc:mysql://localhost:3306/celebrum?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: ${DB_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #     show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.tuype: trace

jwt:
  secret: dcodingdcodingdcodingdcodingdcodingdcodingdcodingdcoding
