spring:
#  datasource:
#    url:
#    username: dcoding
#    password:
#    driver-class-name:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #     show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.tuype: trace