#spring:
#  datasource:
#    url: jdbc:mysql://acg6138.czyfxvmdjeap.ap-northeast-2.rds.amazonaws.com:3306/jocoding?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: acg6138
#    password: wjddn6138
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto : create
#      default_batch_fetch_size: 100
#    properties:
#      hibernate:
#        format_sql: true
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dcoding
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      default_batch_fetch_size: 100
    properties:
      hibernate:
        #     show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secret: dcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcodingdcoding
