name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.SERVER_IP }} # 인스턴스 IP
          username: ${{ secrets.SSH_USER }} # 우분투 아이디
          key: ${{ secrets.SSH_PRIVATE_KEY }} # ec2 instance pem key
          port: ${{ secrets.SSH_PORT }} # 접속포트
          script: |            
            cd celebrem/Celebrem_backend
            git remote update
            git pull origin main
            chmod +x gradlew
            ./gradlew clean build -x test --parallel
            
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest 

    steps:
      - name: deploy server
        timeout-minutes: 2
        continue-on-error: true
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }} 
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod +x deploy.sh
            ./deploy.sh
            sleep 5
            exit 0
